#Threshold
CPU_Threshold=10 # Keeping the value low for testing purpose
MEMORY_Threshold=10# Keeping the value low for testing purpose
DISK_Threshold=10# Keeping the value low for testing purpose

#Service 
SERVICE="nginx"

#Log Files
LOG_FILE="logs/system.logs"

#Alert
Enable_ALERTS=true

